name: Second workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World 2nd workflow!"
      - name: multiline commands
        run: |
          node -v
          npm -v
          python -V
